### ISSUE TITLE
Implement pushLightUserData

### ISSUE THREAD

**Issue by orange451** [hollow-cube/luau-java#3]
Any timeline to get this function implemented? I am trying to set a global variable in lua environment to a java backed object, and as far as I know, this is the way to do it.

In LuaStateImpl class, this throws an UnsupportedOperationException

**Comment by CryptForge** [comment]
You can just use normal userdata as it functions mostly the same as light userdata due to the way the bindings are implemented.

The actual userdata made by this library is always a `long` which is a reference to java object.

**Comment by orange451** [comment]
Thank you, I was not aware of this API. This is what I tried, which seems to work:
```java
            thread.newUserData(new Object());
            thread.setGlobal("script");
```
