### ISSUE TITLE
How To "Sandbox" A Userdata?

### ISSUE THREAD

**Issue by orange451** [hollow-cube/luau-java#4]
I have a class as follows:
```java
public class TestClass {
    private String ComputeThing() {
        return "Hello From Java";
    }
}
```

In lua I want to call the function like such:
```lua
local value = testObject:ComputeThing()
print(value)
```

However I want to send the instance of TestClass to lua as a Userdata:
```java
var testObject = new TestClass();
thread.newUserData(testObject);
thread.setGlobal("testObject");
```

This above code will set testObject as a userdata representing TestClass in lua, which is great. However, how can I actually call the methods on TestClass? What if I want to limit certain functions from being called?

In LuaJava, the implementation I went with was extending LuaTable, and defining all of my functions via rawset(key, value) from the Java side. As such, there is no additional setup to calling the "Table"s functions

Is there a similar paradigm with luau-java?

**Comment by mworzala** [comment]
Hi!

Metatables are the mechanism for exposing information from a userdata object. You can use the `__index` meta method on the userdata metatable to expose properties. In Lua, the syntax `testObject:ComputeThing()` can be thought of as `testObject['ComputeThing'](testObject)`, or fully expanded to `testObject.metatable.__index(testObject, 'ComputeThing')(testObject)` (note that metatable is not actually a property on userdata, just for example purposes).

Given the above, we can implement your example something like the following:
```java
public class TestClass {
    public static void init(LuaState global) {
        LuaFunc computeThingHandle = LuaFunc.preallocate(state -> {
            var instance = (TestClass) state.checkUserDataArg(1, "TestClass");
            state.pushString(instance.ComputeThing());
            return 1;
        });

        // Create the metatable for TestClass
        global.newMetaTable("TestClass");
        global.pushCFunction(state -> {
            var target = state.checkStringArg(2);
            if ("ComputeThing".equals(target)) {
                state.pushCFunction(computeThingHandle, "ComputeThing");
            } else {
                state.pushNil();
            }
            return 1;
        }, "__index");
        global.setField(-2, "__index");
        global.pop(1); // Get rid of metatable

        // Push a userdata of TestClass with the metatable we created above
        global.newUserData(new TestClass());
        global.getMetaTable("TestClass");
        global.setMetaTable(-2);
        global.setGlobal("testObject");
    }

    private String ComputeThing() {
        return "Hello From Java";
    }
}
```

> Note that Lua cannot modify userdata metatables, see [here](https://www.lua.org/pil/28.2.html).

If added to the example when setting up the global state we could execute the following:
```
print("Hello, Luau!")
print(testObject:ComputeThing())

-- Hello, Luau!
-- Hello From Java
```

### More 'advanced'

While the above does work completely fine, Luau adds a shortcut call path for user data objects to reduce the host/lua boundary calls via the `__namecall` meta method. If present, it is used for the `someObject:ComputeThing()` syntax. The above could also use namecall like the following (which would generally be the preferred way to do it):

```java
public class TestClass {
    public static void init(LuaState global) {
        // Create the metatable for TestClass
        global.newMetaTable("TestClass");
        global.pushCFunction(state -> {
            var object = (TestClass) state.checkUserDataArg(1, "TestClass");
            // `nameCallAtom` is only valid inside of a __namecall metamethod call,
            // the first arg to namecall is the object being called on.
            var methodName = state.nameCallAtom();
            if ("ComputeThing".equals(methodName)) {
                state.pushString(object.ComputeThing());
                return 1;
            } else {
                state.pushNil();
                return 1;
            }
        }, "__namecall");
        global.setField(-2, "__namecall");
        global.pop(1); // Get rid of metatable

        // Push a userdata of TestClass with the metatable we created above
        global.newUserData(new TestClass());
        global.getMetaTable("TestClass");
        global.setMetaTable(-2);
        global.setGlobal("testObject");
    }

    private String ComputeThing() {
        return "Hello From Java";
    }
}
```

**Comment by orange451** [comment]
This is fantastic and exactly what I needed, thank you.
